---
- name: Instalar radvd para IPv6
  apt:
    name: radvd
    state: present
    update_cache: yes

- name: Configurar radvd para IPv6
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    mode: '0644'

- name: Reiniciar el servicio radvd
  service:
    name: radvd
    state: restarted
    enabled: yes
