---
- name: Instalar el servidor DHCP
  apt:
    name: isc-dhcp-server
    state: present
    update_cache: yes

- name: Configurar ISC DHCP Server para IPv4
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: '0644'

- name: Reiniciar el servicio ISC DHCP Server
  service:
    name: isc-dhcp-server
    state: restarted
    enabled: yes
