- name: Instalar paquetes para DHCPv6 y RADVD
  ansible.builtin.apt:
    name:
      - isc-dhcp-server
      - radvd
    state: present
    update_cache: yes

- name: Configurar dhcpd6.conf
  ansible.builtin.template:
    src: dhcpd6.conf.j2
    dest: /etc/dhcp/dhcpd6.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart ISC DHCPv6

- name: Asegurar que el servicio se ejecute en IPv6 en interfaz LAN
  ansible.builtin.lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv6='
    line: 'INTERFACESv6="{{ lan_interface }}"'
    create: yes
  notify: Restart ISC DHCPv6

- name: Habilitar modo DHCPv6 en isc-dhcp-server
  ansible.builtin.lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^DHCPDv6='
    line: 'DHCPDv6="yes"'
    create: yes
  notify: Restart ISC DHCPv6

- name: Configurar radvd
  ansible.builtin.template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart radvd

- name: Habilitar y arrancar servicios
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - isc-dhcp-server
    - radvd
