#SPDX-License-Identifier: MIT-0
---
# tasks file for config_netpla_ipv6
- name: Instalar net-tools (opcional, para debug)
  ansible.builtin.apt:
    name: net-tools
    state: present
    update_cache: yes

- name: Configurar Netplan con IPv6 fija en LAN
  ansible.builtin.template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: '0644'

- name: Aplicar configuración de Netplan
  ansible.builtin.command: netplan apply
  register: netplan_result
  changed_when: netplan_result.rc == 0
