[dhcpv6_server]
192.168.1.10 ansible_user=ubuntu ansible_ssh_private_key_file=/path/to/ssh/key

[ubuntu_clients]
192.168.1.20 ansible_user=ubuntu ansible_ssh_private_key_file=/path/to/ssh/key
192.168.1.21 ansible_user=ubuntu ansible_ssh_private_key_file=/path/to/ssh/key
