[dhcpv6_server]
192.168.0.110 ansible_user=admi_yhaja ansible_password=1234 ansible_become=true ansible_become_password=1234

[ubuntu_clients]
192.168.20.21 ansible_user=Yhaja ansible_password=IVbyemcecka6

[windows_clients]
192.168.20.20 ansible_user=yhaja ansible_password=76089152 ansible_connection=winrm ansible_winrm_transport=basic