---
# 1. Listar usuarios existentes
- name: Listar usuarios actuales en la máquina
  ansible.builtin.command: cat /etc/passwd
  register: usuarios_existentes

- name: Mostrar usuarios actuales
  ansible.builtin.debug:
    msg: "{{ usuarios_existentes.stdout_lines }}"

# 2. Crear usuarios definidos en vars
- name: Crear usuarios
  ansible.builtin.user:
    name: "{{ item.nombre }}"
    shell: /bin/bash
    groups: "{{ 'sudo' if item.admin else '' }}"
    state: present
    create_home: yes
  loop: "{{ usuarios_crear }}"

# 3. Eliminar usuarios definidos en vars
- name: Eliminar usuarios
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: yes
  loop: "{{ usuarios_eliminar }}"