interface enp0s8
{
    AdvSendAdvert on;
    prefix 2005:db8:acad:20::/64
    {
        AdvOnLink on;
        AdvAutonomous on;
    };
    RDNSS 2001:4860:4860::8888 2001:4860:4860::8844
    {
        AdvRDNSSLifetime 3600;
    };
};